name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Install dependencies
        run: |
          npm i -g npm@6
          npm i

      - name: No changes to commit
        run: |
          git status --porcelain
          [[ $(git status --porcelain) ]] && exit 1 || exit 0
      - name: TypeScript check
        run: npx tsc

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
